# Generated by Django 2.2 on 2019-07-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190718_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Booking'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=60),
        ),
    ]
