# Generated by Django 2.2 on 2019-07-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190718_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='booked',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='airline.Booking'),
        ),
    ]
