# Generated by Django 2.2 on 2019-07-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190724_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Booking'),
        ),
    ]
