# Generated by Django 2.2 on 2019-07-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190726_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingBy',
        ),
    ]
