# Generated by Django 2.2 on 2019-07-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelling',
            name='flight_image',
            field=models.URLField(default=''),
        ),
    ]
