# Generated by Django 2.2 on 2019-07-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_travelling_flight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelling',
            name='flight_image',
            field=models.URLField(default='https://media.apnarm.net.au/media/images/2018/01/05/imagev172581b44162efca316c368ceb9332a48-de5o2q14aokk572qjp2_ct1880x930.jpg'),
        ),
    ]
