# Generated by Django 2.2 on 2019-07-30 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_auto_20190726_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2019, 7, 30)),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
