# Generated by Django 2.2 on 2019-07-30 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_auto_20190730_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 30, 14, 42, 38, 277018, tzinfo=utc)),
        ),
    ]
