# Generated by Django 2.2 on 2019-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_auto_20190730_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(max_length=20),
        ),
    ]
